# Generated by Django 4.1.4 on 2022-12-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('categories', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('tagline', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=128)),
                ('world_premiere', models.DateField()),
                ('budget', models.IntegerField()),
                ('fees_in_usa', models.IntegerField()),
                ('fees_in_world', models.IntegerField()),
                ('url', models.SlugField(unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(related_name='film_actor', to='actors.actors')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories')),
                ('directors', models.ManyToManyField(related_name='film_director', to='actors.actors')),
                ('genres', models.ManyToManyField(to='genre.genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
