# Generated by Django 4.1.4 on 2023-01-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
